
create table student(
id number(20,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
first_name varchar2(45) NOT NULL,
last_name varchar2(45) NOT NULL,
email varchar2(45) NOT NULL
);


INSERT INTO student VALUES (1,'Mary','Public','mary@luv2code.com');
INSERT INTO student VALUES (2,'John','Doe','john@luv2code.com');
INSERT INTO student VALUES (3,'Ajay','Rao','ajay@luv2code.com');
INSERT INTO student VALUES (4,'Bill','Neely','bill@luv2code.com');
INSERT INTO student VALUES (5,'Maxwell','Dixon','max@luv2code.com');

